### ISSUE TITLE
Python3?

### ISSUE THREAD

**Issue by maxhutch** [globusonline/transfer-api-client-python#5]
Any plans for Python3 support?  Right now, I'm [going through the ssh interface](maxhutch/nek-workflow/globus.py), but this would be better.

**Comment by bd4** [comment]
No plans for Python3 support so far - can you install python 2.7 in your environment? Most Linux distributions are pretty good at allowing both to coexist peaceably.

**Comment by maxhutch** [comment]
I'd like to tie this into other python packages that only support python3.

**Comment by bd4** [comment]
Ah ok - it's not a priority for us but we'll definitely accept patches, and will get to it eventually. The trick is going to be making it work in both Python2 (2.6+) and Python3.X.

**Comment by gutmann** [comment]
Any status update on this?  I see the PR that looks incomplete still, I'm kind of surprised nobody has a python3 implementation working.  Python 2.7 will no longer be maintained starting January 1, 2020.  

https://pythonclock.org

**Comment by bd4** [comment]
See the new library https://github.com/globus/globus-sdk-python , which supports both 2.7 and 3.3+.

**Comment by gutmann** [comment]
Thanks, I'll take a look.  You might want to update the globus online docs to reference that library instead of this one if it is now the preferred version, e.g. https://docs.globus.org/api/transfer/

**Comment by karlito-go** [comment]
Thanks, we will update the docs in the next release.
